name: Build macOS Executable

on:
  push:
    branches:
      - main  # Compila automáticamente al hacer push en la rama "main"

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Configurar el entorno
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Generar el ejecutable
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed main_exe.py

      # Subir el ejecutable como artefacto
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS-executable
          path: dist/main_exe
